name: salatak
description: "تطبيق صلاتك لقضاء الصلاة"
publish_to: 'none'
version: 2.1.0+3

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  supabase_flutter: ^2.8.0
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
