name: salatak
description: "تطبيق صلاتك لقضاء الصلاة"
publish_to: 'none'
version: 3.0.0+4

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  supabase_flutter: ^2.8.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_timezone: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#0E7C66"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
